credentials:
  usernames:
    testuser:
      name: Test User
      password: '$2b$12$KIXQZ8xDq1v5P5gI6k5Q1uXzkPSAfqk0YQl/1qep0lH7OROx1A2Bi'  # "testpass"
cookie:
  name: cyclepilot_auth
  key: some_random_key_here
  expiry_days: 7
preauthorized:
  emails:
    - test@example.com
